.PHONY: clean All

All:
	@echo "----------Building project:[ A6_remDupes - Debug ]----------"
	@cd "A6_remDupes" && "$(MAKE)" -f  "A6_remDupes.mk"
clean:
	@echo "----------Cleaning project:[ A6_remDupes - Debug ]----------"
	@cd "A6_remDupes" && "$(MAKE)" -f  "A6_remDupes.mk" clean
