.PHONY: clean All

All:
	@echo "----------Building project:[ A4_Queues - Debug ]----------"
	@cd "A4_Queues" && "$(MAKE)" -f  "A4_Queues.mk"
clean:
	@echo "----------Cleaning project:[ A4_Queues - Debug ]----------"
	@cd "A4_Queues" && "$(MAKE)" -f  "A4_Queues.mk" clean
