.PHONY: clean All

All:
	@echo "----------Building project:[ A1_Exercise2 - Debug ]----------"
	@cd "A1_Exercise2" && "$(MAKE)" -f  "A1_Exercise2.mk"
clean:
	@echo "----------Cleaning project:[ A1_Exercise2 - Debug ]----------"
	@cd "A1_Exercise2" && "$(MAKE)" -f  "A1_Exercise2.mk" clean
